### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by cafespore** [the-cult-of-integral/discord-raidkit#102]
When prompted to choose Anubis or Quetesh,when entering 1 or 2,the app crashes.However,Osiris don't.

To Reproduce

1. Go to 'the app
2. Enter option "1 or 2"
3. Press enter

**Expected behavior**
It shouldn't crash,it should take us to the prompted tool.

**Lenovo Ideapad 3 AMD Ryzen 5**
 - OS: Windows 10 (AtlasOS)
 - Version:Latest

**Comment by the-cult-of-integral** [comment]
@cafespore I'm unable to reproduce with my bot config: what is your bot config when it crashes?

**Comment by Thugstage** [comment]
I'm having this same issue. Log: INFO - 12/04/2024 02:32:51 :: config.py - DRConfig.prompt_config - No config file found, prompting for config values
WARNING - 12/04/2024 02:33:08 :: PyNaCl is not installed, voice will NOT be supported
INFO - 12/04/2024 02:33:08 :: logging in using static token
CRITICAL - 12/04/2024 02:33:08 :: Discord Raidkit v2.4.4.py - NoneType.run_option - Bot failed to login to Discord with error: Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')]

**Comment by the-cult-of-integral** [comment]
Please update to v2.5.0 and let me know if this issue still occurs.

@cafespore @GoBackTo4Chan
