### ISSUE TITLE
Incomplete Discord Token

### ISSUE THREAD

**Issue by GhostYT23** [the-cult-of-integral/discord-raidkit#106]
**Describe the bug**
The Discord token stealer works, but it's incomplete and unusable because three characters are missing at the end, there is no error , part of the token is just missing.

**Comment by the-cult-of-integral** [comment]
Thanks for the heads up; looking into it now!

**Comment by the-cult-of-integral** [comment]
Issue: Osiris token grabber missing the last eleven characters. Likely caused by Discord updating user tokens (*again*).
Working on an urgent fix now.

**Comment by the-cult-of-integral** [comment]
@GhostYT23 This issue should now be fixed as v2.4.5. If the issue is not fixed for you, please open a new issue.

Thank you for letting me know about this issue!
