### ISSUE TITLE
please add tutorial for osirus

### ISSUE THREAD

**Issue by RICEFARMINGPANDA** [the-cult-of-integral/discord-raidkit#111]
hello im having trouble setting up osirus since every time i test the payload the webhook says that there is no token. idk if i setted it up correctly or if there is an issue w the program (ver 2.4.5)

**Comment by the-cult-of-integral** [comment]
Working on v2.5.0 at the moment, investigating issues with the token grabber since a few issues have come up.

**Comment by George1879** [comment]
Yep, same for me.

**Comment by BigBoiiiiiii** [comment]
tutorial yessir.

**Comment by the-cult-of-integral** [comment]
Please attempt to use v2.5.0. If you still encounter an issue with the token grabber, please create a new issue.
@George1879 @RICEFARMINGPANDA
