### ISSUE TITLE
it does not work at all it does not work with the nuke commands or anything how to fix this 

### ISSUE THREAD

**Issue by warvir22** [the-cult-of-integral/discord-raidkit#114]
for example looks like it joined but when i type command in chat example nick_all it shows this nickname is a required argument that is missing.
 when i dont put the nickname but when i put the name like nick_all dumb it does noting

**Comment by Stevfhulk** [comment]
Quick question, How did you start/install it? Because I cant figure out how.

**Comment by the-cult-of-integral** [comment]
> install python in your pc , get the latest relase v 2.5.0 and run the install requiriments and then run program ofc you also have to extrac files before anything

Maybe the reason why it's not working is because you're using a release that does not exist yet :)
