### ISSUE TITLE
No Install requirements

### ISSUE THREAD

**Issue by Stevfhulk** [the-cult-of-integral/discord-raidkit#115]
There is no install requirements file

Version 2.4.5

Screenshot
![Capture](https://github.com/the-cult-of-integral/discord-raidkit/assets/136190670/df005be6-4b61-4a6b-8b1b-80f6da4ee404)

**Comment by the-cult-of-integral** [comment]
Ah, the install requirements is for Python. If you're running the exe, the requirements are in _internal and shouldn't require any installation. Just run the exe in the same location as _internal.
