### ISSUE TITLE
Application not opening

### ISSUE THREAD

**Issue by GhostYT23** [the-cult-of-integral/discord-raidkit#117]
Descriprion : 
I cannot open the application  in the new version 2.4.5 i just click and nothing happens. 
I have no idea if is just a me thing , if u need some test or anything i will help you out.

**Comment by DipWeb1** [comment]
Same

**Comment by the-cult-of-integral** [comment]
Could you try running the application in the command prompt/terminal and seeing the error message? What does it say?

**Comment by GhostYT23** [comment]
It works perfectly fine if i try to open it from cmd but for some reason it doesn't when i just double click it .

**Comment by the-cult-of-integral** [comment]
Ah, well, I'm glad to hear we've found a way to get it working then ^^

As for why it fails when double-clicking, I have no clue; there are too many variables to account for there, lol. For v2.5.0, I'm trying my hand at another GUI (which hopefully won't be bugged as shit like v2.0.0), so maybe that'll work. Until then, enjoy!

**Comment by GhostYT23** [comment]
Good job , keep it up you are doing great . I will for sure be testing the next version aswell and good luck whit the new Gui.
