### ISSUE TITLE
Exe Wont Open

### ISSUE THREAD

**Issue by AgarHeroYT9** [the-cult-of-integral/discord-raidkit#118]
So i click the exe and it just makes a empty text file

please help me.

**Comment by ultrakilled** [comment]
same problem

**Comment by the-cult-of-integral** [comment]
Can you run the exe in cmd prompt to see if any error message shows up? Also can you read the contents of the file?

**Comment by boooo543** [comment]
IT SAID THERE WAS NO FILE NAMED DISCORD CAN YOU JUST HELP FOR ONCE? HOW DO I FIX THIS

**Comment by the-cult-of-integral** [comment]
Please attempt to use v2.5.0. If you still encounter an issue of the program hanging, please create a new issue.
@AgarHeroYT9 @ultrakilled
