### ISSUE TITLE
Nothing opens/runs when I execute the .exe

### ISSUE THREAD

**Issue by pneumatique** [the-cult-of-integral/discord-raidkit#121]
When I execute the .exe, a command prompt opens for a fraction of a second then disappears and creates a text file for me.

![image](https://github.com/the-cult-of-integral/discord-raidkit/assets/106395181/7fc6bd59-9a0b-4bb9-a532-0dd26ba5afc1)

**Comment by the-cult-of-integral** [comment]
Looking into the issue; can't seem to reproduce it, but it's happened for a few people. You are using Windows 10 or 11?

**Comment by LukysGaming** [comment]
Hi, same issue
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19045 N/A Build 19045

**Comment by the-cult-of-integral** [comment]
Do you have a Discord so we can communicate more effectively? @LukysGaming 
If so, add xorbit64

**Comment by TheFactoryMustGrow** [comment]
same problem here, on windows 11

**Comment by GAchievements** [comment]
Same problem after trying on Windows 11 and Windows 10.

**Comment by Mariuszko10** [comment]
Same Windows 8.1 Pro

**Comment by the-cult-of-integral** [comment]
Please attempt to use v2.5.0. If you still encounter an issue of the program hanging, please create a new issue.
@LukysGaming @Mariuszko10 @pneumatique @GAchievements @TheFactoryMustGrow

**Comment by TheFactoryMustGrow** [comment]
HORRAYY
