### ISSUE TITLE
HOW TO RUN IT?

### ISSUE THREAD

**Issue by MOALFOREVER** [the-cult-of-integral/discord-raidkit#123]
**Describe the bug**
I AM NEW TO THESE STUFF BUT HOW CAN I RUN IT?

AND MY SYSTEM IS WINDOWS 10 64-BIT

**Comment by CiannieTheBottom** [comment]
https://github.com/the-cult-of-integral/discord-raidkit?tab=readme-ov-file#installation

**Comment by MOALFOREVER** [comment]
I DOWNLOADED IT,AND I COULD OPEN IT IN PYTHON,WHAT I MUST DO NEXT,LIKE I WANT THE STEPS AFTER DOWNLOADING AND EXTRACT IT

**Comment by boooo543** [comment]
MOALFOREVER bro this github is not a very helpfuly community
