### ISSUE TITLE
Program taking super long time to load, when it used to load instantly.

### ISSUE THREAD

**Issue by kmanb44** [the-cult-of-integral/discord-raidkit#125]
This may sound stupid but I was using the software fine today until around mid day where it would open command prompt, minimise it, then not run anything. I tried what was said about opening the executable through command prompt but that didn't help either. Any ideas?

**Comment by kmanb44** [comment]
To add: I have also tried re-downloading the latest version, and restarted my laptop, and that didn't work, but I'm guessing it's something on my end?

**Comment by kmanb44** [comment]
To add again: I left the program open after it minimised and left it and after a few minutes it does eventually work, although it no longer opens instantly.

**Comment by the-cult-of-integral** [comment]
Quite a broad range of possible causes. I think for the next release I will keep out the automatic search for updates; perhaps that is what is causing the issue... who knows?

**Comment by the-cult-of-integral** [comment]
Please attempt to use v2.5.0. If you still encounter an issue of the program hanging, please create a new issue.
@kmanb44
