### ISSUE TITLE
v2.4.4 problem

### ISSUE THREAD

**Issue by R17as** [the-cult-of-integral/discord-raidkit#127]
i can't launch the v2.4.5 even with the cmd prompt so i use the 2.4.4 and the / cmd are working fine but the cmd of anubis are not working.
If i use a cmd that doesn't exist the bot say "Error Command does not exist" but when i use a real cmd nothing append and for some i got the error "member is a required argument that is missing" or "Member @mypseudo not found".

If you can help me it would be nice.

**Comment by the-cult-of-integral** [comment]
Not sure what could be causing the error regarding member ... not found. This is an error usually returned by the Discord API itself when it can't find a member in a server (guild), and is thus external.

Do you get any errors when trying to launch via the CMD prompt for v2.4.5? If so what are they?

**Comment by R17as** [comment]
when i try to launch via the cmd prompt nothing append idk why.
Do you know how can i make the anubis cmd work bc it still doing the same error with nothing appening when i use them.

**Comment by the-cult-of-integral** [comment]
Please attempt to use v2.5.0. If you still encounter an issue of the program hanging, please create a new issue.
@R17as
