### ISSUE TITLE
Does not load, just hangs in the background.

### ISSUE THREAD

**Issue by Jambo199** [the-cult-of-integral/discord-raidkit#132]
I download the tool, extracted it, and opened it, but it does not open and only hangs around in the background
Opening with cmd, ends up with the same outcome
**Expected behavior**
Hang around in the background

**Desktop (please complete the following information):**
 - OS: Windows 10 pro

**Additional context**

**Comment by Mariuszko10** [comment]
same
Windows 8.1 Pro

**Comment by the-cult-of-integral** [comment]
Working on new release to fix
