### ISSUE TITLE
Guys i think its fake

### ISSUE THREAD

**Issue by microG460** [the-cult-of-integral/discord-raidkit#133]
He might be fishing for downloads as any type o  EXE i tried does not work. and he refuses to help people so its clear

**Comment by brianscottjr** [comment]
it itself is a token grabber prob

**Comment by kmanb44** [comment]
> He might be fishing for downloads as any type o EXE i tried does not work. and he refuses to help people so its clear

it does work lmao

**Comment by Sericao** [comment]
> > He might be fishing for downloads as any type o EXE i tried does not work. and he refuses to help people so its clear
> 
> it does work lmao

BRO HOW. I've been trynna set it up for a good while now

**Comment by kmanb44** [comment]
idk i mean ive only ever used the token login feature

**Comment by Mariuszko10** [comment]
it just opens a little cmd window and goes away with a empty log

**Comment by kmanb44** [comment]
U mean it did work for me a few times but it's stopped working randomly and now does what you describe. Although if you leave it open long enough (many minutes) it will eventually load correctly. (At least it did for me)

**Comment by the-cult-of-integral** [comment]
I'm still unable to reproduce this bug lol. Working on a new version with a GUI atm, maybe that'll fix the issue
