### ISSUE TITLE
discord raidkit error

### ISSUE THREAD

**Issue by lol2362362** [the-cult-of-integral/discord-raidkit#137]
**Describe the bug**
whenever i try to open the raidkit thru command stroke i have an error (yesterday it worked fine)

**Expected behavior**
for the raidkit to open

**Screenshots**
![image](https://github.com/user-attachments/assets/573c923b-d5be-4a09-aea3-172a78b6a89d)

**Desktop (please complete the following information):**
 Windows 11
 Chrome
 23H2 ig

**Comment by the-cult-of-integral** [comment]
Please attempt to use v2.5.0. If you still encounter an issue of the program not getting the correct JSON back from the Github API, please create a new issue.
@lol2362362
