### ISSUE TITLE
Admin cmd problem

### ISSUE THREAD

**Issue by R17as** [the-cult-of-integral/discord-raidkit#143]
Firstly i wan't to thank you for you'r update and you have done a really good job the new look is nice and softer and the cmd and osiris are working well and fast.
The reason of this bug report is that when i use the admin cmd it says that the user id is invalid even if i put a real id from someone on the server so maybe the problem is me and i did smth wrong but idk why it won't work.
And i'm struggling with the nsfw cmd if you can help me it would be cool.
Hope you can help me and have a nice day.

**Comment by R17as** [comment]
I use discord raidkit since the 2.3.3 and i have never be disappointed thank for keeping it alive.

**Comment by the-cult-of-integral** [comment]
I'm glad you've liked the update so far.

I'll look now to see if I can replicate the issue regarding the admin command.

In the meantime, as for the NSFW commands, ensure you have Qetesh selected as the Raider type for Horus in the bot configuration screen. Next, run the bot and see if the slash command `/see` is available on the server. If it isn't, then the command sync probably hasn't finished/hasn't worked. This is a Discord thing - basically, an application syncs commands to servers globally when a tree.sync is called, and it can only do this occasionally or something, and sometimes takes a while to update - again, it's just a weird Discord thing. If `/see` is available, it can be used to show NSFW images. If you get a message telling you this needs to be done in an NSFW channel, either do it in an NSFW channel or use another slash command, `/toggle-only-nsfw`.

**Comment by R17as** [comment]
Ok thank you and yea the problem for the nsfw command should come from the sync

**Comment by the-cult-of-integral** [comment]
Can confirm this is a silly bug lmao - it is doing `lblMemberID.text().strip()` when it should be doing `leMemberID.text().strip()`. God damn it, intellisense.

**Comment by R17as** [comment]
Damn that's fast

**Comment by the-cult-of-integral** [comment]
@R17as Discord: `_Catterall_`
