### ISSUE TITLE
In server commands "not found"

### ISSUE THREAD

**Issue by Liambruce440** [the-cult-of-integral/discord-raidkit#144]
the commands are working on the tool, but the "safe" commands are not found in the server itself?
also member ID doesnt work. i am assuming thats the users id?

**Comment by Liambruce440** [comment]
any update? just the admin function im after and it says no user matches this member id

**Comment by the-cult-of-integral** [comment]
Still looking into it. I'll let you know if I can reproduce the issue and update the issue labels. @Liambruce440

**Comment by Liambruce440** [comment]
thank you. can i just clarify that member id is actually the discord accounts user id?

**Comment by the-cult-of-integral** [comment]
@Liambruce440 Yes, member id should be the discord accounts user id you get from right clicking and clicking copy id. A screenshot of the GUI would be nice, showing the guild id and member id provided.

**Comment by Liambruce440** [comment]
do you have somewhere i can dm you this?

**Comment by the-cult-of-integral** [comment]
Discord: `_Catterall_`
