### ISSUE TITLE
I DONT HAVE PYTHON

### ISSUE THREAD

**Issue by WooRepo** [the-cult-of-integral/discord-raidkit#154]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by the-cult-of-integral** [comment]
Then install Python or run the executable you mong.

**Comment by WooRepo** [comment]
k sorry

**Comment by Miygteet** [comment]
Hello @WooRepo you can install the latest realease of python here: https://www.python.org/downloads/
