### ISSUE TITLE
Completed Anubis Error

### ISSUE THREAD

**Issue by PlutonIGS** [the-cult-of-integral/discord-raidkit#28]
Hello,
Sorry for my english but i am frensh

if i start the code i ave that error type : `Multiple exceptions: [Errno 111] Connect call failed ('::1', 5432, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 5432)`

Thanks You

**Comment by Catterall** [comment]
It is highly likely that your machine has too many TCP connections. Potential solutions include opening fewer TCP connections or increasing the range of ephemeral ports.
