### ISSUE TITLE
Problem With Installation.

### ISSUE THREAD

**Issue by peepeeslayer46** [the-cult-of-integral/discord-raidkit#43]
Hey team! So when I  run the install requirements (console) it installs all the requirements, but doesn't open up the program, so then I click on Discord Raidkit v2.2.1 Console.py, the CMD prompt opens up for a split second then closes, I tried using the latest version of Python, that didn't work, So I tried downgrading back to Python 9.3.7. Any help would be appreciated!

**Comment by the-cult-of-integral** [comment]
Please run the program directly from CMD itself, so you can see the error before CMD closes. Then, paste the error here. Thank you.

**Comment by peepeeslayer46** [comment]
I had multiple installations of python installed, it seemed to fix a problem I had with the GUI. not console though. I'm using the GUI version now but thank you for attempting to help :]
