### ISSUE TITLE
can this work on a mac?

### ISSUE THREAD

**Issue by zelochris** [the-cult-of-integral/discord-raidkit#45]
Im using a mac and cant find any way to run the install_requirements.bat file on mac or am i just not looking hard enough? would really appreciate a solution to this. thank you.

**Comment by Raigis** [comment]
install windows

**Comment by the-cult-of-integral** [comment]
I have no idea whether this can work on Macintosh or Linux. Never tried it on a virtual machine. The install requirements bat file contains just a pip command, so you could open the file with your text editor, copy the contents, and then run it in whatever terminal you have.
