### ISSUE TITLE
It does not install discord.py

### ISSUE THREAD

**Issue by Cossegosse** [the-cult-of-integral/discord-raidkit#46]
when I try to run the app I get the error
 Traceback (most recent call last):
  File "C:\Users\User\Desktop\Discord Raidkit v2.3.0\main.py", line 18, in <module>
    from discord.errors import HTTPException, LoginFailure
ModuleNotFoundError: No module named 'discord'

**Comment by Cossegosse** [comment]
I have installed the install_requirements

**Comment by the-cult-of-integral** [comment]
Send an email to discord-raidkit-12@proton.me with your discord contact details.
