### ISSUE TITLE
While using Anubis, the continue button doesn't work.

### ISSUE THREAD

**Issue by OfficialB** [the-cult-of-integral/discord-raidkit#47]
Everything you need to see is here. I have all the required dependencies & I installed Python correctly.
https://user-images.githubusercontent.com/86677439/186037877-2869d11c-def9-4806-b242-fe4e6a5ab0e0.mp4

**Comment by the-cult-of-integral** [comment]
Send your discord contact details to
discord-raidkit-12@proton.me

**Comment by eduoliihezz** [comment]
It happens to me, but when it works, it appears an error

**Comment by the-cult-of-integral** [comment]
A lack of privileged intents causes this issue.
I will look into providing an error message for this error in the next update.
