### ISSUE TITLE
Does not proceed after Checking Updates

### ISSUE THREAD

**Issue by FASTANDEXTREME** [the-cult-of-integral/discord-raidkit#50]
Installed the kit, Python and GIT was required. I ran the installer bat and later ran the main.py. Only one line came that was Checking for updates and it disappears and nothing comes up again, It was done through both python and CMD.

**Comment by the-cult-of-integral** [comment]
Turns out there is an input statement following the update routine. This input statement should be within the routine, not outside the routine.

For now, just press enter to continue to the main screen. 2.3.2 will fix this issue.
