### ISSUE TITLE
Issues between latest and previous releases/

### ISSUE THREAD

**Issue by ConceptualFear** [the-cult-of-integral/discord-raidkit#51]
So, I've tried downloading both the latest release and that specific release you are using in your video (v2.0.0). 

That release runs just fine except it doesn't like to start the bot. The latest release doesn't include the same GUI, which isn't a big deal. but it also has the same issue. I've also made a comment in the video for you.

**Comment by the-cult-of-integral** [comment]
Please explain what you mean by "it doesn't like to start the bot".

**Comment by the-cult-of-integral** [comment]
Old and no response
