### ISSUE TITLE
cant install requirements

### ISSUE THREAD

**Issue by deceased1** [the-cult-of-integral/discord-raidkit#55]
when i run `install_requirements.bat` it shows this error -

note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for multidict
Failed to build yarl multidict
ERROR: Could not build wheels for yarl, multidict, which is required to install pyproject.toml-based projects

I've searched everywhere for a fix but cant find one.

**Comment by deceased1** [comment]
> https://aka.ms/vs/17/release/vc_redist.x64.exe your missing this

i downloaded it and it didn't work yet again except this time when running `main.py` it says as follows:

    from discord.errors import HTTPException, LoginFailure, PrivilegedIntentsRequired
ModuleNotFoundError: No module named 'discord'

**Comment by owolo** [comment]
> ModuleNotFoundError: No module named 'discord'

pip install discord.py

**Comment by BumbleBee-2349** [comment]
have you already used pip install -r requirements.txt ?


Sent from my iPhone

On 24 Nov 2022, at 19:07, Owol ***@***.***> wrote:

﻿

ModuleNotFoundError: No module named 'discord'

pip install discord.py

**Comment by deceased1** [comment]
@owolo @BumbleBee-2349 i've done both of those

**Comment by BumbleBee-2349** [comment]
still have error?

Sent from my iPhone

On 25 Nov 2022, at 10:37, deceased ***@***.***> wrote:

﻿

@owolo<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fowolo&data=05%7C01%7C%7C9ab3d8fd44ba48df354208daced114a1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638049694625364180%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=A6aMbRrtbpc4ZBDFjOR0H8te0HJJA8uaeBjxeGueZM4%3D&reserved=0> @BumbleBee-2349<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBumbleBee-2349&data=05%7C01%7C%7C9ab3d8fd44ba48df354208daced114a1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638049694625520418%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ew8SV27BAackI1fGZ9Deuktmn9QOpPLNEBpMVayMQyM%3D&reserved=0> i've done both of those

**Comment by the-cult-of-integral** [comment]
```
ERROR: Failed building wheel for multidict
Failed to build yarl multidict
ERROR: Could not build wheels for yarl, multidict, which is required to install pyproject.toml-based projects
```
This issue is likely to be unrelated to this project. I'll do some further testing now.

**Comment by the-cult-of-integral** [comment]
Test Results:
Ran `python -m venv venv` to create a virtual environment to test installing modules. All modules are installed OK, with no errors during the installation process.

In conclusion, this issue is caused by something unrelated to this project. Apologies.
