### ISSUE TITLE
cannot run main.py file

### ISSUE THREAD

**Issue by ilikebeingbuttfucked** [the-cult-of-integral/discord-raidkit#57]
the main.py is in the notepad application therefore i cannot run it
![Screenshot 2023-01-01 212147](https://user-images.githubusercontent.com/121778097/210191181-4e57cf18-7e9c-4582-ad0f-1cfa644464ce.png)

**Comment by RattyTheRatter** [comment]
download python

**Comment by the-cult-of-integral** [comment]
This is an unsolvable bug in all Windows 9 releases. Please upgrade.
