### ISSUE TITLE
DO NOT DOWNLOAD

### ISSUE THREAD

**Issue by Jambo199** [the-cult-of-integral/discord-raidkit#61]
I have dragged the zip file to https://virustotal.com/ and it comes up with trojans

**Comment by the-cult-of-integral** [comment]
Thank you to @MayiVT for the common sense.

**Comment by Rocketlauncha56** [comment]
dunno windows security and winrar didnt even wanna touch it

**Comment by Jambo199** [comment]
> Thank you to @MayiVT for the common sense.

Trust me, this is a virus

**Comment by Rocketlauncha56** [comment]
> > Thank you to @MayiVT for the common sense.
> 
> Trust me, this is a virus

yep this is a trojan that tries to attack your files.

**Comment by Jambo199** [comment]
> > > Thank you to @MayiVT for the common sense.
> > 
> > Trust me, this is a virus
> 
> yep this is a trojan that tries to attack your files.

Windows Defender Really helped me lol
