### ISSUE TITLE
osiris 

### ISSUE THREAD

**Issue by dcxml** [the-cult-of-integral/discord-raidkit#63]
Hello, I have a problem with osiris, I'm testing this application and I launched payload.py, now my webhook sends my discord token to the designated channel every time I start the computer, how can I stop it?

**Comment by the-cult-of-integral** [comment]
The registry entry is in `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run` - you should remove Osiris.

The hidden payload will be in `C:\Users\{username}\{name you gave for folder\name you gave for file}.pyw`
