### ISSUE TITLE
This happens when i chose Anubis and Qetesh

### ISSUE THREAD

**Issue by Eromero121212** [the-cult-of-integral/discord-raidkit#68]
![image](https://user-images.githubusercontent.com/97339710/229613753-7baa4a89-e302-41d4-9a86-93bbcdd29691.png)
Can anyone give detailed info cuz i dont understand discord stuff much

[raidkit.log](https://github.com/the-cult-of-integral/discord-raidkit/files/11142030/raidkit.log)

**Comment by the-cult-of-integral** [comment]
03/04/2023 20:34:18 - ERROR - Invalid token provided

Provide a valid bot token.
