### ISSUE TITLE
Nothing but Osiris works

### ISSUE THREAD

**Issue by Hubgit168** [the-cult-of-integral/discord-raidkit#70]
When I open the kit, i open anubis, and it gave me what eventually seemed to be edit anubis/qetesh, and i gave it what it wanted until i got to enter the statuses to cycle through, which as im writing i realize its discord status, but i didnt know at the time so i put "est, etest" and i finished it and it took me to main menu where I hit 1 again and it said "Privileged Intents Required

Enter anything to continue:" and so i did, i tried pressing 1 again and the application crashed. it logs in using a static token

**Comment by the-cult-of-integral** [comment]
> "Privileged Intents Required"

You must go to discord.com/developers, navigate to your bot, and enable all intents.

![Privileged Gateway Intents](https://user-images.githubusercontent.com/98130822/233778507-98ce4ee8-c587-4a42-8114-af474548d583.png)

**Comment by the-cult-of-integral** [comment]
@Hubgit168 Closing this issue as it seems to be related to your bot setup rather than the application itself. Please create a new issue if you have any further problems!
