### ISSUE TITLE
I cant get the discord bots, to actually make this program work.

### ISSUE THREAD

**Issue by magn840g** [the-cult-of-integral/discord-raidkit#76]
**Describe the bug**
please help. Can someone send a discord link to the bots?

**Comment by chethanyadav456** [comment]
> **Describe the bug** please help. Can someone send a discord link to the bots?

Can you elaborate your issuse.
First check your bot token is valid or not.

**Comment by magn840g** [comment]
the problem is I cant get the bots into the server so I can get their token, Can you send the discord link so I can add the discord bot to the server? all of them would be nice.

**Comment by the-cult-of-integral** [comment]
I don't think you understand how this program works.

You get the bot application from https://discord.com/developers
