### ISSUE TITLE
Unknown Error When I Use !admin Command

### ISSUE THREAD

**Issue by WarFiN123** [the-cult-of-integral/discord-raidkit#82]
!admin @myusername OWNER
!admin myusername OWNER
!admin <myusername> <OWNER>

They all produce Error
                            An unknown error has occurred.

**Comment by WarFiN123** [comment]
Also for nuke command*

**Comment by the-cult-of-integral** [comment]
The unknown error issue for nuke has been solved as of v2.4.4.

I could not reproduce the error for admin, though I did get that error for admin when I deliberately used incorrect syntax. The syntax is `<prefix>admin @<member> <rolename>`, I believe - you must tag the member so the program can get the Member object, not just type out the username.
