### ISSUE TITLE
File does not show up in Downloads and refuses to extract

### ISSUE THREAD

**Issue by snifflygoldfish** [the-cult-of-integral/discord-raidkit#88]
Every time I attempt to open or extract the file, it tells me it is no longer in my files and lists the file as being 0 bytes. It does not show up in my Downloads either, meaning I cannot delete it. I've tried moving it to the Recycle Bin manually, but it refuses to move anywhere.

**Comment by the-cult-of-integral** [comment]
Sounds like an anti-virus issue of some kind. Please try setting the downloads location for your browser to an excluded folder or attempt to exclude your current downloads folder and see if that works.
