### ISSUE TITLE
Opens and closes instantly

### ISSUE THREAD

**Issue by yourlocalsogga** [the-cult-of-integral/discord-raidkit#92]
i installed python and all the Microsoft libraries
but it just crash or opens and crash

it says

LoadLibrary: pyinstaller formatmessagew Failed.

**Comment by the-cult-of-integral** [comment]
Just cloned the repo and installed the modules; was able to run the program fine. 

I have no idea what you're talking about when you say you installed all the "Microsoft libraries." And it definitely opens and crashes for you - it can't crash without running first.

Just use the executable if you can't get it to work with Python for whatever reason.
