### ISSUE TITLE
Please enable the following intents in the Discord Developer Portal... and nothing

### ISSUE THREAD

**Issue by Esteban312542** [the-cult-of-integral/discord-raidkit#93]
![image](https://github.com/the-cult-of-integral/discord-raidkit/assets/96830805/f2942905-f375-4f7f-847f-3ad5709c2251)

Could someone help? I have no clue what to enable???

**Comment by danyalassi** [comment]
in ur discord bot search in yt to how

**Comment by the-cult-of-integral** [comment]
@Esteban312542 

https://github.com/the-cult-of-integral/discord-raidkit/wiki/Getting-started-with-Discord-Raidkit
