### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Justman100** [the-cult-of-integral/discord-raidkit#95]
On Microsoft Windows

> File "...\Raid\Discord Raidkit v2.4.4\Discord Raidkit v2.4.4.py", line 17, in <module>
    import conf.config as conf
ModuleNotFoundError: No module named 'conf.config'

**Comment by nacho-cheeze** [comment]
you can use the command "pip install conf.config"

**Comment by Justman100** [comment]
> you can use the command "pip install conf.config"

> ERROR: Could not find a version that satisfies the requirement conf.config (from versions: none)
ERROR: No matching distribution found for conf.config

**Comment by the-cult-of-integral** [comment]
`conf.config` is not an external module. I'm unable to reproduce this issue, but it sounds like something to do with a missing file, or a file being in the wrong location, hence why Python cannot find it.

**Comment by Justman100** [comment]
> `conf.config` is not an external module. I'm unable to reproduce this issue, but it sounds like something to do with a missing file, or a file being in the wrong location, hence why Python cannot find it.

I just cloned it and tried to install it directly
