### ISSUE TITLE
Please make a tutorial!

### ISSUE THREAD

**Issue by AllDaGames** [the-cult-of-integral/discord-raidkit#99]
Hey I have set up the bot but im a bit confused about how to use it. Is there a discord server or somthing? Also I saw a tutorial online but it was from a year ago and is the only one. So I was wondering could you make an updated tutorial about how to use it and installation and post it on YouTube? Also in the tutorial I saw when they ran the app a guy came up but when ive been using it ive just been using command windows.

**Comment by the-cult-of-integral** [comment]
Ah, the dreaded v2.0.0 GUI... and its many bugs.

Don't worry. I'll find the time to do a tutorial in the future. Until then, the [Wiki](https://github.com/the-cult-of-integral/discord-raidkit/wiki/Getting-started-with-Discord-Raidkit#linking-a-discord-bot-to-discord-raidkit) may be of some assistance.

**Comment by IndianGamer1313** [comment]
nigga make a tutorial quick

**Comment by BigBoiiiiiii** [comment]
tutorial pls

**Comment by the-cult-of-integral** [comment]
I've released v2.5.0. Yes, the tutorial is still being worked on. v2.5.0 is a relatively major release, hence the lack of tutorial making during its progress... @IndianGamer1313 @BigBoiiiiiii @AllDaGames

**Comment by the-cult-of-integral** [comment]
@AllDaGames @BigBoiiiiiii @IndianGamer1313 @sluwm 

[The Discord Raidkit Wiki has been updated for v2.5.1.](https://github.com/the-cult-of-integral/discord-raidkit/wiki)

Those who prefer videos over reading might have to wait a bit longer. In any case, I'll close this issue.
